version: "3.2"
services:
  data_science:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
      - ./.gcloud:/app/.gcloud
      - /app/node_modules
    ports:
      - "8008:8008"
    stdin_open: true
    tty: true
    depends_on:
      - afl_data
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=.gcloud/keyfile.json
      - PYTHONPATH=./src
      - PYTHON_ENV=local
    command: python3 app.py
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    env_file: .env
    command: Rscript app.R
  notebook:
    image: augury_data_science:latest
    volumes:
      - ./:/app
      - ./.gcloud:/app/.gcloud
    ports:
      - "8888:8888"
    depends_on:
      - data_science
    env_file: .env
    environment:
      - PYTHON_ENV=local
      - GIT_PYTHON_REFRESH=silence
      - GOOGLE_APPLICATION_CREDENTIALS=.gcloud/keyfile.json
    command: kedro jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
  mlflow:
    image: augury_data_science:latest
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - data_science
    command: mlflow server -h 0.0.0.0 --backend-store-uri sqlite:////app/db/mlflow.db --default-artifact-root ./mlruns
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/root/db
