version: "3.2"
services:
  data_science:
    build: .
    volumes:
      - ./:/app
      - ./.gcloud:/app/.gcloud
      - ${HOME}/.aws:/app/.aws
      - /app/node_modules
    ports:
      - "8008:8008"
    stdin_open: true
    tty: true
    depends_on:
      - afl_data
    env_file: .env
    environment:
      - PYTHON_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=.gcloud/keyfile.json
      - AWS_SHARED_CREDENTIALS_FILE=.aws/credentials
      - PYTHONPATH=./src
    command: npx serverless offline
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    ports:
      - "8080:8080"
    depends_on:
      - browser
    stdin_open: true
    tty: true
    env_file: .env
    command: Rscript app.R
  browser:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - "4444:4444"
  notebook:
    image: augury_data_science:latest
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    depends_on:
      - data_science
    environment:
      - PYTHON_ENV=development
      - GIT_PYTHON_REFRESH=silence
    command: kedro jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
  mlflow:
    image: augury_data_science:latest
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - data_science
    command: mlflow server -h 0.0.0.0 --backend-store-uri sqlite:////app/db/mlflow.db --default-artifact-root ./mlruns
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/root/db
