service: augury

custom:
  environment: ${file(./env.js):env}
  serverless-offline:
    host: 0.0.0.0
    port: 8008

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: ap-southeast-2
  memorySize: 1024
  timeout: "540s"
  environment:
    PYTHON_ENV: ${self:custom.environment.python_env}
    PYTHONPATH: ./src
    AFL_DATA_SERVICE: ${self:custom.environment.afl_data_service}
    GCPF_TOKEN: ${self:custom.environment.gcpf_token}
    GCR_TOKEN: ${self:custom.environment.gcr_token}

plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  exclude:
    - ./**
  include:
    - conf/**
    - src/augury/**
    - src/setup.py
    - handler.py
    - package-lock.json
    - package.json
    - requirements.txt
    - .kedro.yml

functions:
  predictions:
    handler: handler.predictions
    events:
      - http:
          path: predictions
          method: get
  fixtures:
    handler: handler.fixtures
    events:
      - http:
          path: fixtures
          method: get
  match_results:
    handler: handler.match_results
    events:
      - http:
          path: match_results
          method: get
  ml_models:
    handler: handler.ml_models
    events:
      - http:
          path: ml_models
          method: get
