name: pipelines

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DATA_SCIENCE_SERVICE: ${{ secrets.DATA_SCIENCE_SERVICE }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Request predictions
      - run: |
        curl -H "Authorization: Bearer ${DATA_SCIENCE_SERVICE_TOKEN}" ${DATA_SCIENCE_SERVICE}/predictions
